import { NgModule } from '@angular/core';

import {
  AfterValidator,
  AlphaValidator,
  AlphanumericValidator,
  AsciiValidator,
  Base64Validator,
  BeforeValidator,
  BooleanValidator,
  ByteLengthValidator,
  ContainsValidator,
  CreditCardValidator,
  CurrencyValidator,
  DataUriValidator,
  DateValidator,
  DecimalValidator,
  DivisibleByValidator,
  EmailValidator,
  EqualsValidator,
  FloatValidator,
  FQDNValidator,
  FullWidthValidator,
  HalfValidator,
  HexColorValidator,
  HexaDecimalValidator,
  IntValidator,
  IPValidator,
  ISBNValidator,
  ISINValidator,
  ISO6601Validator,
  JSONValidator,
  LengthValidator,
  LowerCaseValidator,
  MacAddressValidator,
  Md5Validator,
  MobilePhoneValidator,
  MongoIdValidator,
  MultibyteValidator,
  NullValidator,
  NumericValidator,
  SurrogatePairValidator,
  UpperCaseValidator,
  URLValidator,
  UUIDValidator,
  VariableWidthValidator,
  WhiteListedValidator
} from './ng2-validators';

let Validators = [
  AfterValidator,
  AlphaValidator,
  AlphanumericValidator,
  AsciiValidator,
  Base64Validator,
  BeforeValidator,
  BooleanValidator,
  ByteLengthValidator,
  ContainsValidator,
  CreditCardValidator,
  CurrencyValidator,
  DataUriValidator,
  DateValidator,
  DecimalValidator,
  DivisibleByValidator,
  EmailValidator,
  EqualsValidator,
  FloatValidator,
  FQDNValidator,
  FullWidthValidator,
  HalfValidator,
  HexColorValidator,
  HexaDecimalValidator,
  IntValidator,
  IPValidator,
  ISBNValidator,
  ISINValidator,
  ISO6601Validator,
  JSONValidator,
  LengthValidator,
  LowerCaseValidator,
  MacAddressValidator,
  Md5Validator,
  MobilePhoneValidator,
  MongoIdValidator,
  MultibyteValidator,
  NullValidator,
  NumericValidator,
  SurrogatePairValidator,
  UpperCaseValidator,
  URLValidator,
  UUIDValidator,
  VariableWidthValidator,
  WhiteListedValidator ];

@NgModule({
  declarations: Validators,
  exports: Validators
})
export class Ng2ValidatorsModule { }
